### ISSUE TITLE
Question about split in the paper.

### ISSUE THREAD

**Issue by RERV** [TengdaHan/MemDPC#1]
Hi, Tengda
I read your paper and think it is a really good work. Could you tell me which split in UCF101/HMDB51 you choose to train the ssl model and finetune in all your paper tables? 
A. ssl split1, finetune split 1, test split1;  ssl split2, finetune split 2, test split2;  ssl split2, finetune split 2, test split2; then get avg result
B.  ssl split1,  finetune split 1, test split1;  finetune split 2, test split2;  finetune split 2, test split2; then get avg result
C.  ssl split1,  finetune split 1, test split1;  
D. etc.

Thank you!

**Comment by TengdaHan** [comment]
Hi, for both SSL pretrain and evaluation (finetune or freeze backbone), we use UCF/HMDB split 1.
