### ISSUE TITLE
eval/test.py fails to run: np.ndarray.flatten in numpy 1.19

### ISSUE THREAD

**Issue by sebastianlutter** [TengdaHan/MemDPC#11]
Thanks for sharing your code, excellent work!

I run your project in ubuntu20.04, installed python3.7 from backports and with following pip environment:
```
torch==1.4.0
tensorboardX==2.2
opencv-python==4.5.1.48
joblib==1.0.1
tqdm==4.59.0
matplotlib==3.3.4
torchvision==0.5.0
pandas==1.1.5
numpy==1.19.5
opencv_contrib_python==4.5.1.48
```

I did training with RGB stream UCF101 dataset, worked well so far:
```
python3.7 main.py --gpu 0 --net resnet18 --workers 6 --dataset ucf101 --batch_size 32 --img_dim 128 --epochs 500
```

When I execute `eval/test.py`
```
cd eval
MODEL="../memdpc/log_tmp/memdpc_ucf101-128_resnet18_mem1024_bs16_lr0.001_seq8_pred3_len5_ds3/model/model_best_epoch445.pth.tar"
python3.7 test.py --gpu 0 --net resnet18 --dataset ucf101 --center_crop --img_dim 128 --test "${MODEL}"
```

I get this error in `memdpc/dataset.py`:
```
[ . . . ]
  File "../memdpc/dataset.py", line 162, in idx_sampler
    seq_idx = seq_idx.flatten(0)
TypeError: order must be str, not int
```

This is may related to the error:
* https://stackoverflow.com/questions/64027206/what-did-numpys-flatten0-do

I guess you used an older version of numpy so `flatten(0)` worked well for you. In newer versions of numpy you have too choose either 'C', 'F', 'A', or 'K'
To fix I choose:
```
seq_idx.flatten()
```

Which should be default to c-style flattening (`.flatten('C')`), see https://numpy.org/doc/1.19/reference/generated/numpy.ndarray.flatten.html

Is c-style flattening correct here? Or what did you indent to do there?

**Comment by TengdaHan** [comment]
'C-style' is what I need.

In test case, we scan a "window" along the video time axis with half overlap, then load all these frames for processing. e.g. here I want to change `seq_idx` from
```
array([[0, 1, 2, 3],
       [2, 3, 4, 5],
       [4, 5, 6, 7]])
```
to 
```
array([0, 1, 2, 3, 2, 3, 4, 5, 4, 5, 6, 7])
```

**Comment by sebastianlutter** [comment]
Thanks a lot
