### ISSUE TITLE
Hidden state is needed for prediction? 

### ISSUE THREAD

**Issue by CYKorea** [TengdaHan/MemDPC#14]
As i read the paper, GRU takes several previous clips (not predicted) and propagates a hidden state through them for 'pred step' predictions.
But, in your implementation, as i know, GRU takes only one clip and predicts sequential clips.
I wonder it can yield following problems

1) Zero-initialized hidden states will be used for all inputs of any case.
 - For the first prediction, the zero-initialized state acts as just noise. Then, why do we need to use GRU, not conv blocks?
2) Big quality difference between predictions by their distances from the input.
 - Does it need sequential predictions from one clip? How about one prediction per one clip?

I hope it does not bother you. And I would really appreciate your answer. 
Thanks.

**Comment by TengdaHan** [comment]
https://github.com/TengdaHan/MemDPC/blob/d7dbbf0dc6ec4aa8ff9a5dc8c189d78f4e5e34a7/memdpc/model.py#L102 in this line, GRU consumes the "past" clips, usually 5 clips, then get a hiddle state in L104, before predicting the future 3 clips. 

i.e. when N = 8, self.pred_step = 3, L102 will slice the feature by [0:5]. I think your concerns won't happen.

**Comment by CYKorea** [comment]
Ah ha! I misunderstood those line.

Thank you for your answer.
