### ISSUE TITLE
Exactly what Acc is normal during the training?

### ISSUE THREAD

**Issue by Wolfybox** [TengdaHan/MemDPC#15]
I noticed that the acc computed for validation during the training is actually assessing the retrieval performance of the feature blocks using dot-product similairty. I was wondering exactly how high the val-acc should be during the training ? (e.g. for the UCF101)

**Comment by TengdaHan** [comment]
I think you're referring to this acc: https://github.com/TengdaHan/MemDPC/blob/d7dbbf0dc6ec4aa8ff9a5dc8c189d78f4e5e34a7/memdpc/model.py#L145 

This is equivalent to retrieval **but in the mini-batch** -- the number is not comparable with the 'true' retrieval accuracy which counts over the entire testing set.

About the exact number of this val-acc (top1), as I remember, it is about 60-70% at the end of self-supervised pre-training.
