### ISSUE TITLE
Memory Bank Update

### ISSUE THREAD

**Issue by DeepRunner** [TengdaHan/MemDPC#16]
Hi Tengda,
May I know how do you update the value of memory bank? The reading process from the memory was illustrated in the paper, but the writing process seemed to be omitted.

The parameters \phi for reading process (to produce sampling probability) is learnable.  But are the parameters for the writing also learnable?

Many thanks.

**Comment by TengdaHan** [comment]
Hi! 
The memory bank is created as learnable parameters (https://github.com/TengdaHan/MemDPC/blob/master/memdpc/model.py#L41). It's trained end-to-end with other components of the network, so it will be "written" by backprop. 
Hope it helps.
