### ISSUE TITLE
cannot run correctly for UCF101

### ISSUE THREAD

**Issue by xmengli** [TengdaHan/MemDPC#3]
Hi Thanks so much for sharing the wonderful code. 
I have a problem, in dataset.py file, 
`self.video_info = video_info.drop(drop_idx, axis=0)`, 

this step will filter out all the videos, self.video_info will become empty. 
Is there anything wrong?

**Comment by xmengli** [comment]
Is that because the "csv" file should be generated after all the "frames" file and "flow" file?

**Comment by TengdaHan** [comment]
Hi, the order is correct. First, the content from csv is read (contains two columns: `video_path` and `number_of_frames`). Second, check the video length and drop too short videos. Only a few videos will be dropped. 
On my side the code works ok. If all video paths are dropped, I suggest checking the csv file you generated, is the `number_of_frames` column normal?

**Comment by xmengli** [comment]
How long do you think it takes to generate the "frames" and "flow" files? Does it take more than 2 days?

**Comment by TengdaHan** [comment]
For extracting frame and optical flow from raw video ([src/extract_ff.py](https://github.com/TengdaHan/MemDPC/blob/master/process_data/src/extract_ff.py)), it takes a few hours for UCF101 totally. 

After that, collecting stats into csv file ([src/write_csv.py](https://github.com/TengdaHan/MemDPC/blob/master/process_data/src/write_csv.py)) takes a few seconds. 

Or if you have your own video dataloader for UCF101, it's fine to use your own version as long as the shape of tensor, the sampling of frames and the data augmentation are the same.

**Comment by xmengli** [comment]
Actually I already took more than 2 days to run extract_ff.py file. The current size of "frames" and "flows" are 9.5G and 2.6G, respectively. It is still generating data.... What's wrong here? What is the size for "frames" and "flows" on your side?

**Comment by TengdaHan** [comment]
The frame is about 29GB and flow is about 23GB. I guess the different running time is because of hardware. I store these frames and flows in SSD.

**Comment by xmengli** [comment]
I also store data in SSD. I am using a RTX 2080 8-GPU server and there are no other programs. It is very strange. 
I wonder if it is possible to share these frames and flows data? 

Many thanks!

**Comment by TengdaHan** [comment]
That's strange. Sorry I cannot share the UCF101 data due to potential copyright issue.
One alternative solution is, you can manually make the extraction parallel again, like splitting the 101 classes into 10 parts, let each process extract ~10 classes. Hope this could be faster. 

If have more questions, feel free to ask.

**Comment by justlovebarbecue** [comment]
Hi Tengda,

I followed your instructions to preprocess data for CoCLR using code here, and I also met a similar problem, one class of ucf101 data roughly takes 80~90 mins (seems all the ucf101 may need more than two days for 101 classes).

Do I miss something to setup? (parallel computing? or try to use GPU to extract flow data?)

I saw you provide the flow data for ucf101 in the CoCLR repo. I am considering to revise the extract_ff.py file for only extracting frames and make a LMDB file. Then combine with the flow LMDB file you provided for the following experiments? Is this a feasible way?

BIG THANKS!

**Comment by TengdaHan** [comment]
With my setting (probably I'm using a faster CPU), process UCF with flow extraction takes about 0.5-1 day. 
But most of the CPU time was spend on optical flow computation.
Only extracting frames will be much faster, it's a feasible way.

Right now I don't have enough space to share the UCF101-RGB data file, but will try if I get more space.

**Comment by justlovebarbecue** [comment]
Hi Tengda,

Thx for your timely reply. Sure, I will try the second way.

Thanks!

**Comment by TengdaHan** [comment]
You can check here for both RGB & Flow for UCF101 dataset: https://www.robots.ox.ac.uk/~vgg/research/CoCLR/ in the "Support" section. 
Let me know if have problems downloading.

**Comment by justlovebarbecue** [comment]
Hi Tengda, Thanks for your sharing! I will try that accordingly. 
Thanks!
