### ISSUE TITLE
The pretrained model

### ISSUE THREAD

**Issue by zeng-lingyun** [TengdaHan/MemDPC#4]
Hi, a great work！I have run it with my own dataset without pretrain. But the accuracy is low. 
Could you provide the pretrained ResNet2d3d on imagenet, or some pretrained models on other datasets? Thx !

**Comment by TengdaHan** [comment]
In our MemDPC paper, the ResNet2d3d is pretrained on K400 or UCF101 in a self-supervised way. I am doing a final check before releasing our pretrained models, hope to release them next week, but they would not be related to ImageNet. 

Did you run MemDPC on your own video dataset? What contrastive accuracy did you get? If you train longer, the contrastive accuracy will go higher.
