### ISSUE TITLE
question about the memory bank

### ISSUE THREAD

**Issue by Cory-M** [TengdaHan/MemDPC#8]
Hi, thank you for sharing the great work and well-structured code - I have a quick question that, how you get the value of the memory bank? According to the code, is that just a bank of random initialized vectors? If it is just random initialized vectors, have you done any ablation study on how sensitive the model is, in term of the memory bank initialization?
Thanks so much!

**Comment by TengdaHan** [comment]
Hi! 
* Value of memory bank -- Yes they are randomly initialized [here](https://github.com/TengdaHan/MemDPC/blob/master/memdpc/model.py#L41), and they are trainable parameters.
* How sensitive the model is, in terms of initialization -- I didn't try ablation study here. But we have a possibly relevant visualization in the paper appendix Fig. 8, where the left shows the magnitude of memory slots. Actually, many memory slots are 'muted' after training (have almost all-0 values). 

Hope it helps.
