### ISSUE TITLE
Unable to run K400 training due to gpu memory constraint

### ISSUE THREAD

**Issue by liuhualin333** [TengdaHan/MemDPC#9]
Hi Tengda,

I try to run this self-supervised training command `python main.py --gpu 0,1,2,3 --net resnet34 --dataset k400 --batch_size 16 --img_dim 224 --epochs 200` on a 4-gpu machine with 16 GB memory on each gpu. It seems that there is an out-of-memory issue. I wonder if you have any alternative command or solution for this. Thank you!

Best Regards,
Hualin

**Comment by TengdaHan** [comment]
Hi! Our machine has 22GB memory per GPU. Just try to reduce batch_size slightly to fit your memory. Results won't be affected much.
